packages:
  - '.'
allowBuilds:
  '@nestjs/core': true
  '@scarf/scarf': true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@nestjs/core'
  - '@scarf/scarf'
  - sharp
  - unrs-resolver
